spring:
  application:
    name: ${APPLICATION_NAME:dianaloginregister}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/testdb}
      auto-index-creation: true
      uuid-representation: standard

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:test@example.com}
    password: ${MAIL_PASSWORD:testpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.data.mongodb: info

brand:
  name: "Diana Global"
  frontend-url: "https://www.dianaglobal.com.br"
  logo-url: "https://www.andescoresoftware.com.br" # troque aqui quando quiser

google:
  oauth:
    enabled: ${GOOGLE_OAUTH_ENABLED:false}  # defina true no Heroku quando quiser ativar
    # GOOGLE_CLIENT_ID vem do ambiente (sem default aqui de propósito)

application:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForJWTTokenGeneration1234567890}
  brand:
    name: ${BRAND_NAME:Diana Global}
    logo-url: "https://www.andescoresoftware.com.br/AndesCore.jpg"
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
  confirmation:
    minutes: 45            # expiração do token
    cooldown-seconds: 60   # intervalo mínimo entre reenvios
    max-per-day: 5         # teto diário por dia

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    display-request-duration: true
    try-it-out-enabled: true
